Repository Nexters/www-iOS, pull requests merged in 2023-02, with the labels that each got.

#10 Tuist 적용
  .gitignore
  Plugins/WWW/Package.swift
  Plugins/WWW/Plugin.swift
  Plugins/WWW/ProjectDescriptionHelpers/LocalHelper.swift
  Plugins/WWW/Sources/tuist-my-cli/main.swift
  Projects/App/Project.swift
  Projects/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/Contents.json
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/App/Sources/Application/Info.plist
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Application/Utils/Base/BaseViewModel.swift
  Projects/App/Sources/Application/Utils/Extension/UIStackView+.swift
  Projects/App/Sources/Application/Utils/Extension/UIView+.swift
  Projects/App/Sources/Data/DTO/User/SampleRequestDTO.swift
  Projects/App/Sources/Data/DTO/User/SampleResponseDTO.swift
  Projects/App/Sources/Data/Network/EndPoint/SampleEndpoint.swift
  Projects/App/Sources/Data/Repositories/SampleDAO.swift
  Projects/App/Sources/Domain/Entities/SampleEntity.swift
  Projects/App/Sources/Domain/Interfaces/User/SampleRepository.swift
  Projects/App/Sources/Domain/UseCases/User/SampleUseCase.swift
  Projects/App/Sources/Presentation/Common/SampleButton.swift
  Projects/App/Sources/Presentation/Main/SampleViewController.swift
  Projects/App/Sources/Presentation/Main/SampleViewModel.swift
  Tuist/Config.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Workspace.swift
  www.xcodeproj/project.pbxproj
  www.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  www.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  www.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  www.xcodeproj/xcuserdata/chanheejeong.xcuserdatad/xcschemes/xcschememanagement.plist
  www/Resources/Info.plist
  wwwTests/wwwTests.swift
  wwwUITests/wwwUITests.swift
  wwwUITests/wwwUITestsLaunchTests.swift
Labels: 🛠 SETTING

#25 [FEAT] 네트워크 관련 기본세팅
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Common/ModelType.swift
  Projects/App/Sources/Common/RxMoya.swift
  Projects/App/Sources/Data/DTO/User/LoginRequestDTO.swift
  Projects/App/Sources/Data/DTO/User/LoginResponseDTO.swift
  Projects/App/Sources/Data/Network/UserAPI+Request.swift
  Projects/App/Sources/Data/Network/UserAPI.swift
  Projects/App/Sources/Data/Repositories/UserDAO.swift
  Projects/App/Sources/Domain/Entities/CommonResponse.swift
  Projects/App/Sources/Domain/Interfaces/User/UserRepository.swift
  Projects/App/Sources/Domain/UseCases/User/JoinUserUseCase.swift
  Projects/App/Sources/Domain/UseCases/User/SampleUseCase.swift
  Projects/App/Sources/Presentation/Home/SampleViewController.swift
  Projects/App/Sources/Presentation/Home/SampleViewModel.swift
  Projects/App/Sources/Utils/Constants/APIConstants.swift
  Projects/App/Support/Info.plist
  www.xcodeproj/project.pbxproj
Labels: ✨ FEAT

#28 [Feat] 최소인원설정 UI 및 데이터 바인딩
  Projects/App/Resources/Assets.xcassets/Stepper/Contents.json
  Projects/App/Resources/Assets.xcassets/Stepper/add.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Stepper/add.imageset/add.svg
  Projects/App/Resources/Assets.xcassets/Stepper/add_fill.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Stepper/add_fill.imageset/add_fill.svg
  Projects/App/Resources/Assets.xcassets/Stepper/delete.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Stepper/delete.imageset/delete.svg
  Projects/App/Resources/Assets.xcassets/Stepper/delete_fill.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Stepper/delete_fill.imageset/delete_fill.svg
  Projects/App/Sources/Domain/UseCases/Join/Host/JoinHostUseCase.swift
  Projects/App/Sources/Presentation/Common/Components/Input/Stepper.swift
  Projects/App/Sources/Presentation/Home/SampleViewController.swift
  Projects/App/Sources/Presentation/Join/MinUser/MinUserViewController.swift
  Projects/App/Sources/Presentation/Join/MinUser/MinUserViewModel.swift
  Projects/App/Sources/Utils/Extension/Assset+.swift
Labels: 💄 UI, ✨ FEAT

#31 [Feat] 장소입력 UI 및 데이터 바인딩
  Projects/App/Resources/Assets.xcassets/delete_green.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/delete_green.imageset/delete_green.svg
  Projects/App/Resources/Assets.xcassets/plus_black.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/plus_black.imageset/plus_black.svg
  Projects/App/Resources/Assets.xcassets/plus_gray.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/plus_gray.imageset/plus_gray.svg
  Projects/App/Sources/Domain/Entities/Place/Place.swift
  Projects/App/Sources/Domain/Entities/Place/WrappedPlace.swift
  Projects/App/Sources/Domain/UseCases/Join/Guest/JoinGuestUseCase.swift
  Projects/App/Sources/Domain/UseCases/Join/Host/JoinHostUseCase.swift
  Projects/App/Sources/Presentation/Common/Components/Cell/BasicChipCell.swift
  Projects/App/Sources/Presentation/Common/Components/Cell/DeleteChipCell.swift
  Projects/App/Sources/Presentation/Common/Components/Cell/SelfSizingCollectionViewCell.swift
  Projects/App/Sources/Presentation/Common/Components/Input/PlustTextFieldView.swift
  Projects/App/Sources/Presentation/Home/SampleViewController.swift
  Projects/App/Sources/Presentation/Join/Place/PlaceViewController.swift
  Projects/App/Sources/Presentation/Join/Place/PlaceViewModel.swift
  Projects/App/Sources/Presentation/Join/UserName/UserNameViewModel.swift
  Projects/App/Sources/Utils/Extension/Assset+.swift
  Projects/App/Sources/Utils/Extension/RxRelay+.swift
Labels: ✨ FEAT

#34 [Feat] 약속방생성완료 UI 및 모션
  Projects/App/Resources/Assets.xcassets/WWW/Contents.json
  Projects/App/Resources/Assets.xcassets/WWW/completion.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/WWW/completion.imageset/completion.png
  Projects/App/Resources/Assets.xcassets/WWW/donut.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/WWW/donut.imageset/donut.png
  Projects/App/Resources/Assets.xcassets/WWW/heart_big.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/WWW/heart_big.imageset/heart_big.png
  Projects/App/Resources/Assets.xcassets/WWW/heart_small.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/WWW/heart_small.imageset/heart_small.png
  Projects/App/Resources/Assets.xcassets/WWW/monster.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/WWW/monster.imageset/monster.png
  Projects/App/Resources/Assets.xcassets/link_green.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/link_green.imageset/link_green.svg
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Presentation/Home/SampleViewController.swift
  Projects/App/Sources/Presentation/Home/SampleViewModel.swift
  Projects/App/Sources/Presentation/Join/Completion/CompletionViewModel.swift
  Projects/App/Sources/Presentation/Join/Completion/CompletionViewcController.swift
  Projects/App/Sources/Utils/Extension/Assset+.swift
  Projects/App/Sources/Utils/Helper/WWWAnimationHelper.swift
Labels: 💄 UI, ✨ FEAT

#38 [Feat] 디바이스 사이즈 대응 (feat. DeviceManager)
  Projects/App/Project.swift
  Projects/App/Sources/Utils/Extension/CGFloat+.swift
  Projects/App/Sources/Utils/Extension/Double+.swift
  Projects/App/Sources/Utils/Helper/DeviceManager.swift
  Tuist/Dependencies.swift
Labels: 🛠 SETTING

#39 [Feat] 가능시간대선택 UI
  Projects/App/Resources/Assets.xcassets/Input/Contents.json
  Projects/App/Resources/Assets.xcassets/Input/time_default.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Input/time_default.imageset/time_default.svg
  Projects/App/Resources/Assets.xcassets/Input/time_disabled.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Input/time_disabled.imageset/time_disabled.svg
  Projects/App/Resources/Assets.xcassets/Input/time_selected.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Input/time_selected.imageset/time_selected.svg
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Presentation/Home/SampleViewController.swift
  Projects/App/Sources/Presentation/Join/Time/TimeViewController.swift
  Projects/App/Sources/Presentation/Join/Time/TimeViewModel.swift
  Projects/App/Sources/Presentation/Join/Time/Views/DateStackView.swift
  Projects/App/Sources/Presentation/Join/Time/Views/TimeCheckCell.swift
  Projects/App/Sources/Presentation/Join/Time/Views/TimeStackView.swift
  Projects/App/Sources/Presentation/Join/Time/Views/TimeTextView.swift
  Projects/App/Sources/Utils/Extension/Assset+.swift
  Projects/App/Sources/Utils/Extension/CALayer+.swift
  Projects/App/Sources/Utils/Helper/ScrollPageController.swift
Labels: 💄 UI

#42 [Feat] 메인 홈 화면 UI 및 Data Bind(얼추..?)
  Projects/App/Resources/Assets.xcassets/calendar.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/calendar.imageset/calendar.svg
  Projects/App/Resources/Assets.xcassets/floating_add.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/floating_add.imageset/floating_add.svg
  Projects/App/Resources/Assets.xcassets/floating_cancel.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/floating_cancel.imageset/floating_delete.svg
  Projects/App/Resources/Assets.xcassets/place.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/place.imageset/map-pin.svg
  Projects/App/Resources/Assets.xcassets/promiseFrame.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/promiseFrame.imageset/promiseFrame.svg
  Projects/App/Resources/Assets.xcassets/union1.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/union1.imageset/union1.svg
  Projects/App/Resources/Assets.xcassets/union2.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/union2.imageset/union2.svg
  Projects/App/Resources/Assets.xcassets/users.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/users.imageset/users.svg
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Data/DTO/MeetingMainGetResponseDTO.swift
  Projects/App/Sources/Data/Network/MeetingAPI.swift
  Projects/App/Sources/Data/Repositories/MainHomeDAO.swift
  Projects/App/Sources/Data/Repositories/UserDAO.swift
  Projects/App/Sources/Domain/Entities/MeetingMain.swift
  Projects/App/Sources/Domain/Interfaces/Meeting/MeetingRepository.swift
  Projects/App/Sources/Domain/UseCases/MainHome/MainHomeUseCase.swift
  Projects/App/Sources/Presentation/Common/Components/View/PaddingLabel.swift
  Projects/App/Sources/Presentation/Home/SampleViewController.swift
  Projects/App/Sources/Presentation/MainHome/Cell/MainHomePromiseCell.swift
  Projects/App/Sources/Presentation/MainHome/MainHomeViewController.swift
  Projects/App/Sources/Presentation/MainHome/MainHomeViewModel.swift
  Projects/App/Sources/Presentation/MainHome/Subview/MainHomeDimView.swift
  Projects/App/Sources/Presentation/MainHome/Subview/MainHomeEmptyPromiseView.swift
  Projects/App/Sources/Utils/Constants/MeetingEnum.swift
  Projects/App/Sources/Utils/Constants/UserDefaultKeyCase.swift
  Projects/App/Sources/Utils/Constants/Window.swift
  Projects/App/Sources/Utils/Extension/Assset+.swift
  Projects/App/Sources/Utils/Extension/UIButton+.swift
  Projects/App/Sources/Utils/Extension/UIImage+.swift
  Projects/App/Sources/Utils/Extension/UILabel+.swift
  Projects/App/Sources/Utils/Extension/UIView+.swift
Labels: 🥚 STORY, 💄 UI, ✨ FEAT

#48 투표 시작 / 종료 Alert View
  Projects/App/Resources/Assets.xcassets/votingBox.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/votingBox.imageset/votingBox.png
  Projects/App/Sources/Presentation/Common/Components/View/VotingAlertView.swift
  Projects/App/Sources/Utils/Extension/Assset+.swift
Labels: 💄 UI, ✨ FEAT

#49 어디서 UI
  Projects/App/Resources/Assets.xcassets/chevron_left.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/chevron_left.imageset/chevron_left 1.svg
  Projects/App/Resources/Assets.xcassets/delete_green.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/delete_green.imageset/delete_green.svg
  Projects/App/Resources/Assets.xcassets/info.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/info.imageset/info.svg
  Projects/App/Resources/Assets.xcassets/link.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/link.imageset/link.svg
  Projects/App/Resources/Assets.xcassets/link_green.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/link_green.imageset/link_green.svg
  Projects/App/Resources/Assets.xcassets/plus_black.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/plus_black.imageset/plus_black.svg
  Projects/App/Resources/Assets.xcassets/plus_gray.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/plus_gray.imageset/plus_gray.svg
  Projects/App/Resources/Colors.xcassets/WWWMint.colorset/Contents.json
  Projects/App/Sources/Domain/Entities/Place/Place.swift
  Projects/App/Sources/Presentation/Home/SampleViewController.swift
  Projects/App/Sources/Presentation/Room/PlaceVote/PlaceVoteCell.swift
  Projects/App/Sources/Presentation/Room/PlaceVote/PlaceVoteViewController.swift
  Projects/App/Sources/Utils/Extension/CALayer+.swift
  Projects/App/Sources/Utils/Extension/UIColor+.swift
  Projects/App/Sources/Utils/Extension/UIView+.swift
  www.xcodeproj/project.pbxproj
Labels: 💄 UI

#52 캘린더 화면 UI
  Projects/App/Project.swift
  Projects/App/Sources/Presentation/Join/Calendar/CalendarItems.swift
  Projects/App/Sources/Presentation/Join/Calendar/CalendarViewController.swift
  Projects/App/Sources/Presentation/Join/Calendar/CalendarViewModel.swift
  Tuist/Dependencies.swift
Labels: 🐣 TASK, 💄 UI, ✨ FEAT

#56 설정 화면 UI 작업, 진입점 작업
  Projects/App/Resources/Assets.xcassets/settings.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/settings.imageset/settings.svg
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Presentation/MainHome/MainHomeViewController.swift
  Projects/App/Sources/Presentation/Setting/SettingViewController.swift
  Projects/App/Sources/Presentation/Setting/SettingViewModel.swift
  Projects/App/Sources/Utils/Constants/UserDefaultKeyCase.swift
  Projects/App/Sources/Utils/Extension/Assset+.swift
Labels: 💄 UI, ✨ FEAT

#57 약속방 참여자 UI 구현
  Projects/App/Resources/Assets.xcassets/profileBadge.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/profileBadge.imageset/profileBadge.png
  Projects/App/Resources/Assets.xcassets/profileImg.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/profileImg.imageset/profileImg.png
  Projects/App/Sources/Domain/Entities/User.swift
  Projects/App/Sources/Presentation/Room/Participants/ParticipantCell.swift
  Projects/App/Sources/Presentation/Room/Participants/RoomParticipantsViewController.swift
  Projects/App/Sources/Presentation/Room/Participants/RoomParticipantsViewModel.swift
  Projects/App/Sources/Utils/Extension/Assset+.swift
Labels: 💄 UI, ✨ FEAT

#59 [Feat] 참가하기 플로우 연결 및 자잘한 버그수정
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Presentation/Join/Calendar/CalendarViewController.swift
  Projects/App/Sources/Presentation/Join/Calendar/CalendarViewModel.swift
  Projects/App/Sources/Presentation/Join/Completion/CompletionViewModel.swift
  Projects/App/Sources/Presentation/Join/Completion/CompletionViewcController.swift
  Projects/App/Sources/Presentation/Join/MinUser/MinUserViewController.swift
  Projects/App/Sources/Presentation/Join/MinUser/MinUserViewModel.swift
  Projects/App/Sources/Presentation/Join/Place/PlaceViewController.swift
  Projects/App/Sources/Presentation/Join/Place/PlaceViewModel.swift
  Projects/App/Sources/Presentation/Join/RoomCode/RoomCodeViewController.swift
  Projects/App/Sources/Presentation/Join/RoomName/RoomNameViewController.swift
  Projects/App/Sources/Presentation/Join/Time/TimeViewController.swift
  Projects/App/Sources/Presentation/Join/Time/TimeViewModel.swift
  Projects/App/Sources/Presentation/Join/UserName/UserNameViewController.swift
  Projects/App/Sources/Presentation/Join/UserName/UserNameViewModel.swift
  Projects/App/Sources/Presentation/MainHome/Subview/MainHomeDimView.swift
  Projects/App/Sources/Presentation/Setting/SettingViewController.swift
Labels: 🐛 BUG, ✨ FEAT

#61 [UI] 그래픽 요소 추가
  Projects/App/Resources/Assets.xcassets/WWW/bubble.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/WWW/bubble.imageset/bubble.png
  Projects/App/Resources/Assets.xcassets/WWW/suitcase.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/WWW/suitcase.imageset/suitcase.png
  Projects/App/Sources/Presentation/Join/Place/PlaceViewController.swift
  Projects/App/Sources/Presentation/Join/RoomCode/RoomCodeViewController.swift
  Projects/App/Sources/Presentation/Join/RoomName/RoomNameViewController.swift
  Projects/App/Sources/Presentation/Join/UserName/UserNameViewController.swift
  Projects/App/Sources/Utils/Extension/Assset+.swift
Labels: 💄 UI

#65 [Feat] 참가자로 참여하기 네트워크 연결
  Projects/App/Sources/Common/RxMoya.swift
  Projects/App/Sources/Data/DTO/Meeting/MeetingCodeCheckResponseDTO.swift
  Projects/App/Sources/Data/DTO/Meeting/MeetingJoinRequestDTO.swift
  Projects/App/Sources/Data/DTO/Meeting/MeetingJoinResponseDTO.swift
  Projects/App/Sources/Data/DTO/Meeting/MeetingMainGetResponseDTO.swift
  Projects/App/Sources/Data/Error/JoinMeetingError.swift
  Projects/App/Sources/Data/Network/Meeting/MeetingAPI+Request.swift
  Projects/App/Sources/Data/Network/Meeting/MeetingAPI.swift
  Projects/App/Sources/Data/Network/User/UserAPI+Request.swift
  Projects/App/Sources/Data/Network/User/UserAPI.swift
  Projects/App/Sources/Data/Repositories/MeetingJoin/JoinMeetingDAO.swift
  Projects/App/Sources/Domain/Entities/Meeting/MeetingInfoToJoin.swift
  Projects/App/Sources/Domain/Entities/Place/Place.swift
  Projects/App/Sources/Domain/Entities/Place/WrappedPlace.swift
  Projects/App/Sources/Domain/Entities/Time/SelectedTime.swift
  Projects/App/Sources/Domain/Interfaces/Meeting/MeetingJoinRepository.swift
  Projects/App/Sources/Domain/UseCases/Join/Guest/JoinGuestUseCase.swift
  Projects/App/Sources/Domain/UseCases/Join/Host/JoinHostUseCase.swift
  Projects/App/Sources/Presentation/Join/Place/PlaceViewController.swift
  Projects/App/Sources/Presentation/Join/Place/PlaceViewModel.swift
  Projects/App/Sources/Presentation/Join/RoomCode/RoomCodeViewController.swift
  Projects/App/Sources/Presentation/Join/RoomCode/RoomCodeViewModel.swift
  Projects/App/Sources/Presentation/Join/Time/TimeViewController.swift
  Projects/App/Sources/Presentation/Join/Time/TimeViewModel.swift
  Projects/App/Sources/Presentation/Join/Time/Views/DateStackView.swift
  Projects/App/Sources/Presentation/Join/Time/Views/TimeCheckCell.swift
  Projects/App/Sources/Presentation/Join/UserName/UserNameViewController.swift
  Projects/App/Sources/Presentation/MainHome/MainHomeViewController.swift
  Projects/App/Sources/Utils/Extension/Date+.swift
  Projects/App/Sources/Utils/Extension/DateComponents.swift
Labels: ✨ FEAT

#66 캘린더 UI 및 동작 마무리..
  Projects/App/Project.swift
  Projects/App/Resources/Assets.xcassets/appIcon.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/appIcon.imageset/appIcon.png
  Projects/App/Resources/Assets.xcassets/floating_cancel.imageset/delete.svg
  Projects/App/Sources/Domain/UseCases/Join/Host/JoinHostUseCase.swift
  Projects/App/Sources/Presentation/Join/Calendar/CalendarItems.swift
  Projects/App/Sources/Presentation/Join/Calendar/CalendarViewController.swift
  Projects/App/Sources/Presentation/Join/Calendar/CalendarViewModel.swift
  Projects/App/Sources/Utils/Extension/Assset+.swift
  Tuist/Dependencies.swift
Labels: 🐣 TASK, 💄 UI, ✨ FEAT

#71 캘린더 Usecase 연결
  Projects/App/Sources/Domain/UseCases/Join/Host/JoinHostUseCase.swift
  Projects/App/Sources/Presentation/Join/Calendar/CalendarViewModel.swift
Labels: 🐣 TASK

#74 메인 홈 UI 디테일 작업
  Projects/App/Resources/Assets.xcassets/Yaksoki/Contents.json
  Projects/App/Resources/Assets.xcassets/Yaksoki/yaksoki_eat.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Yaksoki/yaksoki_eat.imageset/yaksoki_eat.png
  Projects/App/Resources/Assets.xcassets/Yaksoki/yaksoki_play.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Yaksoki/yaksoki_play.imageset/yaksoki_play.png
  Projects/App/Resources/Assets.xcassets/Yaksoki/yaksoki_rest.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Yaksoki/yaksoki_rest.imageset/yaksoki_rest.png
  Projects/App/Resources/Assets.xcassets/Yaksoki/yaksoki_work.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Yaksoki/yaksoki_work.imageset/yaksoki_work.png
  Projects/App/Sources/Data/DTO/Meeting/MeetingMainGetResponseDTO.swift
  Projects/App/Sources/Domain/Entities/MeetingMain.swift
  Projects/App/Sources/Domain/UseCases/Join/Host/JoinHostUseCase.swift
  Projects/App/Sources/Presentation/MainHome/Cell/MainHomePromiseCell.swift
  Projects/App/Sources/Presentation/MainHome/MainHomeViewController.swift
  Projects/App/Sources/Presentation/MainHome/Subview/MainHomeEmptyPromiseView.swift
  Projects/App/Sources/Utils/Constants/MeetingEnum.swift
  Projects/App/Sources/Utils/Extension/Assset+.swift
Labels: 💄 UI, ✨ FEAT

#78 MainHome API 연결
  Projects/App/Sources/Data/DTO/Meeting/MeetingMainGetResponseDTO.swift
  Projects/App/Sources/Domain/Entities/MeetingMain.swift
  Projects/App/Sources/Domain/UseCases/MainHome/MainHomeUseCase.swift
  Projects/App/Sources/Presentation/LaunchScreen/LaunchScreenViewController.swift
  Projects/App/Sources/Presentation/MainHome/Cell/MainHomePromiseCell.swift
  Projects/App/Sources/Presentation/MainHome/MainHomeViewController.swift
  Projects/App/Sources/Utils/Constants/MeetingEnum.swift
Labels: ✨ FEAT
